### PR TITLE
Test specifically for voltron/entry.py in install.sh

### LINKED ISSUE #177: More accurate check in install.sh for lldbinit/gdbinit
Grep for `$LLDB_SITE_PACKAGES/voltron/entry.py` etc rather than just `voltron`

### PR DESCRIPTION
**Pull request by Grazfather**
Fixes #177

### CODE REVIEW

**Comment by Grazfather** [comment]
Failure seems related to the write memory functionality and not the install script.

**Comment by snare** [comment]
Yeah, will investigate the test failure, but this will actually break the install script as those variables are tested at the end to determine whether or not anything was added to the (gd|ll)dbinit

**Comment by snare** [comment]
The install script sucks and needs some love

**Comment by Grazfather** [comment]
Ah I was wondering why you set them in the if case. I tested, but only from an existing install. It definitely needs some love. Swapping the two lines and re-adding the hardcoded string will probably fix it, but maybe I'll change the check at the bottom so it doesn't depend on an overloaded variabl.

**Comment by snare** [comment]
Gave it some love :)

**Comment by Grazfather** [comment]
<3

**Pull request merged**
