### PR TITLE
Word memory

### PR DESCRIPTION
**Pull request by devaneal**
This adds a --words/-w flag to the memory view that displays the data as a column of machine words.

### CODE REVIEW

**Comment by snare** [comment]
This looks like it won't display correctly for big endian architectures. I'm also not keen on displaying the ASCII like that - IMO it should still be displayed in the order of the bytes in memory. I'll give it a try and see what can be done.

**Comment by snare** [comment]
Thanks for the PR though, it's definitely a feature I'd like to include.

**Comment by devaneal** [comment]
Now that I think of it, I totally agree on the ascii part - the whole point is to read strings directly from memory. I'm going to look into adding compatibility for big-endian architectures.

**Comment by snare** [comment]
Awesome, thanks. FYI the `target` var set [here](https://github.com/snare/voltron/blob/master/voltron/plugins/view/memory.py#L80) contains `byte_order` and `addr_size` fields.

**Pull request merged**
